export enum localStorageKeys {
  TOKEN_KEY = "token",
  NEWS = "news",
  LANG = "lang",
  TOASTER_ACCEPTED = "ranking/toaster/accepted",
  INDEXATION_TOAST_STATS_ACCEPTED = "indexation/toast/stats/accepted",
  ACTIVE_WEBSITE = "active-website",
  INDEXATION_ONBOARDING_SEEN = "indexation/onboarding/seen",
  REDIRECT_URL_AFTER_LOGIN = "REDIRECT_URL_AFTER_LOGIN",
  ONBOARDING_TODO_SEEN = "onboarding/todo/seen",
  onboarding_seen_health_check = "onboarding_seen_health_check",
  onboarding_seen_todo = "onboarding_seen_todo",
  onboarding_seen_analytics = "onboarding_seen_analytics",
  onboarding_seen_indexation = "onboarding_seen_indexation",
}
