export enum ModalKeys {
  "ai_explainer_modal" = "ai_explainer_modal",
  "tts_modal" = "tts_modal",
  "news-modal" = "news-modal",
  "upsell-confirmation-modal" = "upsell-confirmation-modal",
  "remove-website-confirmation-modal" = "remove-website-confirmation-modal",
  "logs-create-modal" = "logs-create-modal",
  "add-user-to-website-modal" = "add-user-to-website-modal",
  "indexation-auto-modal" = "indexation-auto-modal",
  "organization-create-modal" = "organization-create-modal",
  "change-language-modal" = "change-language-modal",
  "search-gpt-subscription-success-modal" = "search-gpt-subscription-success-modal",
  "indexation-website-bad-setup-on-google-modal" = "indexation-website-bad-setup-on-google-modal",
  "indexation-website-bad-setup-on-google-success-modal" = "indexation-website-bad-setup-on-google-success-modal",
  "pricing-lifetime-access-modal" = "pricing-lifetime-access-modal",
  "todo-add-website-modal" = "todo-add-website-modal",
  "onboarding-modal" = "onboarding-modal",
  "onboarding-article-modal" = "onboarding-article-modal",
  "drawer" = "drawer",
  keywords_add_website_modal = "keywords_add_website_modal",
  keywords_add_keywords_modal = "keywords_add_keywords_modal",
  keywords_calendar_filter_modal = "keywords_calendar_filter_modal",
  feedbacks_nps_score_modal = "feedbacks_nps_score_modal",
}
